# Generated by Django 4.2.7 on 2024-11-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
